### PR TITLE
Eliminate dual feature flags for email send publisher

### LINKED ISSUE #1452: Simplify email send publisher: eliminate dual feature flags and DisabledEmailCommandPublisher
## Problem

The email send publisher currently uses two separate feature flags to route between Kafka and ASB:

1. **`NotificationConfig:EnableSendEmailPublisher`** (Core project) - read at runtime in `EmailNotificationService.SendNotifications()` to decide whether to call the Wolverine publisher or the Kafka producer.
2. **`WolverineSettings:EnableSendEmailPublisher`** (Integrations project) - gates the ASB queue configuration and publisher registration in `WolverineServiceCollectionExtensions`.

This leads to:
- A `DisabledEmailCommandPublisher` that exists only to throw `InvalidOperationException` when the flags are misconfigured (Wolverine publisher enabled in Core but not registered in Integrations).
- Routing logic (`if/else` on the flag) baked into `EmailNotificationService`, coupling Core to transport concerns.
- Two flags that must stay in sync across different config sections, which is error-prone.

## Desired approach

The `feature/1365-email-polling-asb-migration` branch demonstrates the preferred pattern for the email service's `IEmailStatusCheckDispatcher`:

- A single interface is defined in Core with no knowledge of transport.
- In `ServiceCollectionExtensions.RegisterSendingAcceptedPublisher()`, the Wolverine settings are read once and a `useWolverine` boolean determines which implementation to register via an **if/else** block — either the ASB publisher or the Kafka producer.
- No "disabled" placeholder class exists. Exactly one fully-configured transport path is always active.
- Core service code just calls the interface method with no routing logic.

The same pattern is also used in the SMS service (`feature/1364-sms-asb-deliveryreports`), where `ServiceCollectionExtensions` registers `KafkaSmsDeliveryReportPublisher` by default and `WolverineServiceCollectionExtensions` conditionally replaces it with `AsbSmsDeliveryReportPublisher`.

### 1. Create a Kafka-based email command publisher
Create `KafkaEmailCommandPublisher` implementing `IEmailCommandPublisher`. Extract the Kafka produce logic currently inline in `EmailNotificationService.PublishEmailNotificationsViaKafka()`.

### 2. Register the correct publisher at startup using if/else
Following the 1365 pattern, add a private registration method (e.g. in `ServiceCollectionExtensions` or a dedicated extension) that reads `WolverineSettings` once and picks the implementation:

```csharp
private static void RegisterEmailCommandPublisher(IServiceCollection services, IConfiguration config, KafkaSettings kafkaSettings)
{
    IConfigurationSection wolverineSection = config.GetSection(nameof(WolverineSettings));
    WolverineSettings wolverineSettings = wolverineSection.Get<WolverineSettings>() ?? new WolverineSettings();

    bool useWolverine =
        wolverineSettings.EnableWolverine &&
        wolverineSettings.EnableSendEmailPublisher &&
        !string.IsNullOrWhiteSpace(wolverineSettings.EmailSendQueueName);

    services.RemoveAll<IEmailCommandPublisher>();

    if (useWolverine)
    {
        services.AddSingleton<IEmailCommandPublisher, EmailCommandPublisher>();
    }
    else
    {
        services.AddSingleton<IEmailCommandPublisher>(sp =>
            new KafkaEmailCommandPublisher(
                sp.GetRequiredService<IKafkaProducer>(),
                kafkaSettings.EmailQueueTopicName));
    }
}
```

### 3. Remove routing logic from EmailNotificationService
- Delete `PublishEmailNotificationsViaKafka()` and `PublishEmailNotificationsViaWolverine()`.
- Remove the `if (_sendEmailNotificationsViaWolverine)` branch.
- `SendNotifications()` should unconditionally call `_emailCommandPublisher.PublishAsync(...)`.
- Remove the `_sendEmailNotificationsViaWolverine` field and the `IKafkaProducer` / `_emailSendTopicName` dependencies (they move into the Kafka publisher).

### 4. Remove `NotificationConfig:EnableSendEmailPublisher`
- Delete the property from `NotificationConfig`.
- Remove from `appsettings.json` (under the `NotificationConfig` section).
- The only remaining flag is `WolverineSettings:EnableSendEmailPublisher`.

### 5. Delete `DisabledEmailCommandPublisher`
No longer needed — the if/else registration guarantees a real publisher is always registered.

### 6. Update tests
- `DisabledEmailCommandPublisherTests` — delete entirely.
- `EmailNotificationServiceTests` — remove the `sendViaWolverine` parameter and routing assertions. The service always delegates to the injected `IEmailCommandPublisher`.
- Integration test appsettings — remove `NotificationConfig:EnableSendEmailPublisher`.

## Files affected

| File | Action |
|------|--------|
| `Core/Configuration/NotificationConfig.cs` | Remove `EnableSendEmailPublisher` |
| `Core/Services/EmailNotificationService.cs` | Remove routing logic, Kafka deps; always use `_emailCommandPublisher` |
| `Core/Services/DisabledEmailCommandPublisher.cs` | Delete |
| `Core/Extensions/ServiceCollectionExtensions.cs` | Remove `DisabledEmailCommandPublisher` registration |
| `Integrations/Extensions/WolverineServiceCollectionExtensions.cs` | Remove unconditional `RemoveAll`/`AddSingleton` for publisher |
| New: registration method (in existing extensions or new file) | if/else Kafka vs ASB publisher registration |
| New: `Integrations/Publishers/KafkaEmailCommandPublisher.cs` | Extract from `EmailNotificationService` |
| `api/src/Altinn.Notifications/appsettings.json` | Remove `EnableSendEmailPublisher` from `NotificationConfig` |
| `Tests/DisabledEmailCommandPublisherTests.cs` | Delete |
| `Tests/EmailNotificationServiceTests.cs` | Simplify |

### PR DESCRIPTION
**Pull request by martivj**
## Description

The new `KafkaEmailCommandPublisher` should retain the same logic as before. Double check that nothing here is broken during review.

## Related Issue(s)
- #1452

## Verification
- [ ] **Your** code builds clean without any errors or warnings
- [ ] Manual testing done (required)
- [ ] Relevant automated test added (if you find this hard, leave it and we'll help out)
- [ ] All tests run green

## Documentation
- [ ] User documentation is updated with a separate linked PR in [altinn-studio-docs.](https://github.com/Altinn/altinn-studio-docs) (if applicable)

## Summary by CodeRabbit

* **Chores**
  * Removed deprecated send-email config and centralized publisher selection during startup; email sending now always routes through the configured publisher.
* **New Features**
  * Added a Kafka-backed email command publisher and conditional registration to choose the appropriate publisher at runtime.
* **Tests**
  * Added comprehensive tests for the Kafka publisher, removed obsolete disabled-publisher tests, and updated existing tests to the new publishing model.

### CODE REVIEW

File: components/api/src/Altinn.Notifications.Integrations/Kafka/Publishers/KafkaEmailCommandPublisher.cs [hunk 1]
```diff
@@ -0,0 +1,56 @@
...
+
+        var failedEmails = new List<Email>();
+        foreach (var unpublished in unpublishedSerialized)
+        {
+            var deserialized = JsonSerializer.Deserialize<Email>(unpublished, JsonSerializerOptionsProvider.Options);
+            if (deserialized is not null && deserialized.NotificationId != Guid.Empty)
+            {
+                failedEmails.Add(deserialized);
+            }
+        }
```
[the remark this answers is not in the document]
Comment (martivj) [reply components/api/src/Altinn.Notifications.Integrations/Kafka/Publishers/KafkaEmailCommandPublisher.cs:52]: We want errors like this to propagate like it did in the old implementation.

**Comment by eskebab** [comment]
@coderabbitai review

File: components/api/src/Altinn.Notifications.Integrations/Extensions/ServiceCollectionExtensions.cs [hunk 2]
```diff
@@ -103,4 +108,35 @@ public static void AddKafkaHealthChecks(this IServiceCollection services, IConfi
...
+    {
+        IConfigurationSection wolverineSection = config.GetSection(nameof(WolverineSettings));
+        WolverineSettings wolverineSettings = wolverineSection.Get<WolverineSettings>() ?? new WolverineSettings();
+
+        bool useWolverine =
+            wolverineSettings.EnableWolverine &&
+            wolverineSettings.EnableSendEmailPublisher &&
+            !string.IsNullOrWhiteSpace(wolverineSettings.EmailSendQueueName);
+
+        services.RemoveAll<IEmailCommandPublisher>();
```
Comment (Ahmed-Ghanam) [inline components/api/src/Altinn.Notifications.Integrations/Extensions/ServiceCollectionExtensions.cs]: Since `DisabledEmailCommandPublisher` was removed from Core's registration, there is no prior registration to remove when `RegisterEmailCommandPublisher` runs. The `RemoveAll` is harmless but dead code.

**Review by Ahmed-Ghanam — APPROVED** [review]
## Test Session Summary

### Environment

*   **Cluster:** AKS yt01 (Altinn‑Platform‑Test)
*   **Services tested:** `altinn-notifications` (API) and `altinn-notifications-email`
*   **Deployment:** Current branch changes deployed to both services

***

## Test 1 — ASB / Wolverine Mode

**Results**

*   Peak messages on `altinn.notifications.email.send` queue: **36,730**
*   Peak messages on `altinn.notifications.email.check.send.status` queue: **37,070**
*   Email processing: ✅ All messages were successfully consumed and processed
*   Kafka errors: ⚠️ Expected noise (Kafka brokers are intentionally disabled in this configuration)

**Conclusion:**  
ASB/Wolverine processing behaves as expected under load.

***

## Test 2 — Kafka Mode

**Results**

*   ASB queues: ✅ Not used at all
*   Email delivered: **27,681**
*   Email succeeded: **2,735**
*   Email failed: **1**
*   SMS accepted: **15,461**
*   Total notifications processed: **\~45,878**

**Conclusion:**  
Kafka processing works correctly and remains fully isolated from ASB when running in Kafka mode.

***

## Overall Verdict

✅ Both ASB and Kafka pipelines are functioning correctly.  
The changes in this branch behave as expected in both modes, with clean separation between transports and no cross‑contamination.

File: components/api/src/Altinn.Notifications.Integrations/Extensions/ServiceCollectionExtensions.cs (hunk 2 above)
Comment (martivj) [reply components/api/src/Altinn.Notifications.Integrations/Extensions/ServiceCollectionExtensions.cs]: Removed in the most recent commit.
